### PR TITLE
fixed, built, tested, against ocaml 4.07.1, oasis 0.4.11

### PR DESCRIPTION
**Pull request by chetmurthy**
Hi, hope I did this correctly (it's been a while since I hacked with ocaml and oasis).

### CODE REVIEW

**Comment by gildor478** [comment]
Thanks for doing this.

You need to add "BuildDepends: bytes" as well, since you are using this module.

**Comment by chetmurthy** [comment]
Oops sorry, I'll do that and re-send the PR.

**Comment by chetmurthy** [comment]
OK, I think I've pushed the change to the PR branch.

**Comment by gildor478** [comment]
Thanks

**Comment by gildor478** [comment]
I have done a release with your changes + a few other:
https://github.com/gildor478/ocaml-archive/releases/tag/2.8.4%2B3

**Pull request merged**
